@startuml analysis-architecture
!theme plain

package analysis{
    boundary XView
    control XController
    entity XDAO
    entity XModel
}

package front <<Android App>> {
    boundary AndroidViews
    boundary MainActivity
    boundary Fragments
}

package backend <<Room-SQLite>> {
    entity SessionDAO
    entity GameDAO
    entity GameEntity
    entity PropCombDAO
    entity PropCombEntity
}

package app-core <<Maven dependency>> {
    entity CoreSessionDAO <<abstract>>
    boundary CoreViews <<abstract>>
    control CoreControllers
    entity CoreModels
}

' analysis
XView ..> XController
XView ..> XModel
XController ..> XModel
XController ..> XDAO

' front
AndroidViews --> Fragments 
MainActivity ..> Fragments
MainActivity --> AndroidViews

AndroidViews .up.> XView
MainActivity .up.> XView
Fragments .up.> XView

' backend
SessionDAO --> GameDAO
SessionDAO --> PropCombDAO
GameDAO --> GameEntity
PropCombDAO --> PropCombEntity

SessionDAO .up.> XDAO
GameDAO .up.> XDAO
PropCombDAO .up.> XDAO
GameEntity .right.> XModel
PropCombEntity .right.> XModel

' app-core
CoreViews --> CoreControllers
CoreViews --> CoreModels
CoreControllers --> CoreModels
CoreControllers --> CoreSessionDAO

CoreViews .up.> XView
CoreControllers .up.> XController
CoreModels .up.> XModel
CoreSessionDAO .up.> XDAO


